"""The plain-English behaviour vocabulary.

Each behaviour is one (effect id, aura id) pair from Spell.dbc wearing a name a
person can read. The pairs themselves, and the defaults attached to them, come
out of the shipped corpus; this file is the naming and curation layer on top,
because "MOD_DECREASE_SPEED" is not plain English and no amount of statistics
will turn it into "Slow the target down".

Curation also decides what *not* to offer. The corpus is full of effects that
are engine plumbing (SCRIPT_EFFECT, SEND_EVENT), effects that need a C++ script
to mean anything (DUMMY), and effects that would wedge a character if handed to
someone experimenting (POSSESS, TELEPORT). Those are deliberately absent; see
spellweaver/coredefs.py for how the do-nothing ones are detected automatically.

`params` names the knobs the UI exposes for a behaviour, in order:
  amount   EffectBasePoints  - damage, healing, percentage or flat amount
  period   EffectAuraPeriod  - milliseconds between ticks
  radius   EffectRadiusIndex - yards, for area behaviours
  chain    EffectChainTargets- number of extra targets to jump to
  stat/school/power/mechanic/dispel  EffectMiscValue, in the given domain
Duration is a property of the whole spell, not of one effect, so it is a
top-level field rather than a per-behaviour parameter. Radius is likewise
absent: how wide a spell reaches follows from the target the user picks, not
from the behaviour, so it lives in spellweaver/targeting.py.
"""
from collections import namedtuple

Behaviour = namedtuple("Behaviour", "key label category effect aura shape params summary")


def _b(key, label, category, effect, aura, shape, params, summary):
    return Behaviour(key, label, category, effect, aura, shape, tuple(params), summary)


# shape:
#   instant  - happens once, on cast
#   aura     - applies a lasting aura; the spell needs a duration
#   periodic - a lasting aura that ticks; needs duration and period
#   ground   - a persistent area effect anchored to a location
BEHAVIOURS = [
    # --- Damage ---------------------------------------------------------
    _b("damage", "Damage target", "Damage", 2, 0, "instant",
       ["amount"], "Straight spell damage of the spell's school, once, on hit."),
    _b("damage_over_time", "Damage over time", "Damage", 6, 3, "periodic",
       ["amount", "period"], "Ticks damage on the target for the spell's duration. The amount is per tick."),
    _b("damage_ground", "Area damage at a location", "Damage", 27, 3, "ground",
       ["amount", "period"],
       "Leaves a patch on the ground that damages anything standing in it, like Blizzard."),
    _b("weapon_damage_pct", "Weapon damage (percentage)", "Damage", 31, 0, "instant",
       ["amount"], "Damage scaled from the weapon swing, as a percentage. 100 means one normal hit."),
    _b("weapon_damage_plus", "Weapon damage plus an amount", "Damage", 58, 0, "instant",
       ["amount"], "A normal weapon swing with a flat bonus added."),
    _b("weapon_damage_normalised", "Normalised weapon damage", "Damage", 121, 0, "instant",
       ["amount"], "Weapon damage using a normalised speed, so fast and slow weapons behave alike."),
    _b("drain_life", "Drain health", "Damage", 6, 53, "periodic",
       ["amount", "period", "heal_share"],
       "Ticks damage on the target and heals the caster for a share of it."),
    _b("damage_reflect", "Damage attackers", "Damage", 6, 15, "aura",
       ["amount"], "Anyone who strikes the target in melee takes damage back, like Thorns."),
    _b("knock_back", "Knock back", "Damage", 98, 0, "instant",
       ["amount"], "Throws the target away from the caster. The amount is the horizontal speed."),

    # --- Healing --------------------------------------------------------
    _b("heal", "Heal target", "Healing", 10, 0, "instant",
       ["amount"], "Restores health once, on cast."),
    _b("heal_over_time", "Heal over time", "Healing", 6, 8, "periodic",
       ["amount", "period"], "Ticks healing on the target for the spell's duration. The amount is per tick."),
    _b("absorb", "Absorb damage (shield)", "Healing", 6, 69, "aura",
       ["amount", "school"], "Soaks up incoming damage until the shield is used up or expires."),
    _b("restore_power", "Restore resource", "Healing", 30, 0, "instant",
       ["amount", "power"], "Gives back mana, rage, energy or runic power."),
    _b("restore_power_over_time", "Restore resource over time", "Healing", 6, 24, "periodic",
       ["amount", "period", "power"], "Ticks a resource back for the spell's duration."),
    _b("resurrect", "Resurrect", "Healing", 113, 0, "instant",
       ["amount"], "Offers a resurrection to a dead player. The amount is the percentage of health restored."),

    # --- Control --------------------------------------------------------
    _b("stun", "Stun", "Control", 6, 12, "aura",
       [], "The target cannot act or move at all for the duration."),
    _b("root", "Immobilise", "Control", 6, 26, "aura",
       [], "The target cannot move but can still act."),
    _b("fear", "Fear", "Control", 6, 7, "aura",
       [], "The target flees under its own power for the duration."),
    _b("disorient", "Disorient", "Control", 6, 5, "aura",
       [], "The target wanders at random and cannot act, like Blind. Breaks on damage."),
    _b("silence", "Silence", "Control", 6, 27, "aura",
       [], "The target cannot cast spells, but can still use physical abilities."),
    _b("pacify", "Prevent attacking", "Control", 6, 25, "aura",
       [], "The target cannot use melee or ranged attacks, but can still cast."),
    _b("disarm", "Disarm", "Control", 6, 67, "aura",
       [], "The target's main-hand weapon is unusable for the duration."),
    _b("interrupt", "Interrupt casting", "Control", 68, 0, "instant",
       ["amount"], "Stops the target's current cast and locks that school briefly."),
    _b("taunt", "Taunt", "Control", 6, 11, "aura",
       [], "Forces a creature to attack the caster."),
    _b("threat", "Change threat", "Control", 63, 0, "instant",
       ["amount"], "Adds or removes threat with the current target. Negative values shed threat."),
    _b("dispel", "Dispel", "Control", 38, 0, "instant",
       ["amount", "dispel"], "Removes auras of a given type. The amount is how many to strip."),
    _b("immune_mechanic", "Immunity to a control effect", "Control", 6, 77, "aura",
       ["mechanic"], "Makes the target immune to one kind of crowd control, and clears it on apply."),

    # --- Movement -------------------------------------------------------
    _b("slow", "Slow movement", "Movement", 6, 33, "aura",
       ["amount"], "Reduces movement speed by a percentage. Use a negative amount to slow."),
    _b("speed_up", "Increase movement speed", "Movement", 6, 31, "aura",
       ["amount"], "Increases movement speed by a percentage."),

    # --- Attributes -----------------------------------------------------
    _b("mod_stat", "Change a primary stat", "Attributes", 6, 29, "aura",
       ["amount", "stat"], "Adds or removes Strength, Agility, Stamina, Intellect or Spirit."),
    _b("mod_stat_pct", "Change all stats by a percentage", "Attributes", 6, 137, "aura",
       ["amount", "stat"], "Scales primary stats by a percentage."),
    _b("mod_resistance", "Change resistance or armour", "Attributes", 6, 22, "aura",
       ["amount", "school"], "Adds resistance for a school. Choose Physical for armour."),
    _b("mod_max_health", "Change maximum health", "Attributes", 6, 34, "aura",
       ["amount"], "Raises or lowers the target's maximum health."),
    _b("mod_attack_power", "Change attack power", "Attributes", 6, 99, "aura",
       ["amount"], "Adds or removes melee attack power."),
    _b("mod_ranged_attack_power", "Change ranged attack power", "Attributes", 6, 124, "aura",
       ["amount"], "Adds or removes ranged attack power."),
    _b("mod_damage_done_pct", "Change damage dealt", "Attributes", 6, 79, "aura",
       ["amount", "school"], "Scales the damage the target deals, as a percentage."),
    _b("mod_damage_taken_pct", "Change damage taken", "Attributes", 6, 87, "aura",
       ["amount", "school"], "Scales the damage the target takes. Negative values reduce it."),
    _b("mod_healing_taken_pct", "Change healing received", "Attributes", 6, 118, "aura",
       ["amount"], "Scales healing done to the target, as a percentage."),
    _b("mod_healing_done_pct", "Change healing done", "Attributes", 6, 136, "aura",
       ["amount"], "Scales healing the target casts, as a percentage."),
    _b("mod_melee_haste", "Change attack speed", "Attributes", 6, 138, "aura",
       ["amount"], "Scales melee swing speed. Positive is faster."),
    _b("mod_cast_speed", "Change casting speed", "Attributes", 6, 65, "aura",
       ["amount"], "Scales cast times. Negative values slow the target down."),
    _b("mod_melee_crit", "Change melee critical chance", "Attributes", 6, 52, "aura",
       ["amount"], "Adds percentage points of melee crit chance."),
    _b("mod_spell_crit", "Change spell critical chance", "Attributes", 6, 57, "aura",
       ["amount"], "Adds percentage points of spell crit chance."),
    _b("mod_dodge", "Change dodge chance", "Attributes", 6, 49, "aura",
       ["amount"], "Adds percentage points of dodge."),
    _b("mod_parry", "Change parry chance", "Attributes", 6, 47, "aura",
       ["amount"], "Adds percentage points of parry."),
    _b("mod_power_regen", "Change resource regeneration", "Attributes", 6, 85, "aura",
       ["amount", "power"], "Changes how fast a resource refills, per five seconds."),
    _b("mod_threat_pct", "Change threat generated", "Attributes", 6, 10, "aura",
       ["amount", "school"], "Scales threat the target generates. Negative values reduce it."),

    # --- Utility --------------------------------------------------------
    _b("stealth", "Stealth", "Utility", 6, 16, "aura",
       ["amount"], "Hides the target from view until they act or are detected."),
    _b("invisibility", "Invisibility", "Utility", 6, 18, "aura",
       ["amount"], "Makes the target invisible to anyone without matching detection."),
    _b("water_breathing", "Water breathing", "Utility", 6, 82, "aura",
       [], "The target no longer needs to surface for air."),
    _b("safe_fall", "Slow fall", "Utility", 6, 144, "aura",
       ["amount"], "Removes falling damage and slows the descent."),
    _b("feign_death", "Feign death", "Utility", 6, 66, "aura",
       [], "The target appears dead and drops out of combat."),
    _b("transform", "Change appearance", "Utility", 6, 56, "aura",
       ["creature"], "Replaces the target's model with a creature display."),
    _b("mod_scale", "Change size", "Utility", 6, 61, "aura",
       ["amount"], "Scales the target's model by a percentage."),
    _b("summon", "Summon a creature", "Utility", 28, 0, "instant",
       ["amount", "creature"], "Summons a creature that fights for or follows the caster."),
    _b("trigger_spell", "Cast another spell", "Utility", 64, 0, "instant",
       ["trigger"], "Immediately casts a second spell, which does the real work."),
    _b("trigger_spell_periodic", "Cast another spell repeatedly", "Utility", 6, 23, "periodic",
       ["period", "trigger"], "Casts a second spell every tick for the spell's duration."),
    _b("proc_trigger", "Cast a spell on a chance to proc", "Utility", 6, 42, "aura",
       ["trigger"], "While the aura holds, a second spell fires when the target hits or is hit."),
    _b("learn_spell", "Teach a spell", "Utility", 36, 0, "instant",
       ["trigger"], "Permanently teaches the target another spell."),

    # --- Damage (continued) ---------------------------------------------
    _b("damage_pct_health", "Damage over time (share of health)", "Damage", 6, 89, "periodic",
       ["amount", "period"], "Ticks damage equal to a percentage of the target's maximum health."),
    _b("health_leech", "Steal health", "Damage", 9, 0, "instant",
       ["amount", "heal_share"],
       "Damages the target and heals the caster for a share of the damage dealt."),
    _b("drain_mana", "Drain mana over time", "Damage", 6, 64, "periodic",
       ["amount", "period", "gain_share"],
       "Ticks mana off the target and gives a share of it to the caster."),
    _b("power_drain", "Drain resource", "Damage", 8, 0, "instant",
       ["amount", "power", "gain_share"],
       "Takes a resource from the target and gives a share of it to the caster."),
    _b("power_burn", "Burn resource", "Damage", 62, 0, "instant",
       ["amount", "power", "burn_ratio"],
       "Destroys a resource and deals damage for each point destroyed."),
    _b("charge", "Charge to the target", "Damage", 96, 0, "instant",
       ["amount"], "Rushes the caster to the target, closing the gap."),
    _b("leap", "Leap to a location", "Damage", 42, 0, "instant",
       ["amount"], "Throws the caster to the targeted spot."),
    _b("slow_ground", "Slowing patch at a location", "Damage", 27, 33, "ground",
       ["amount", "period"],
       "Leaves a patch on the ground that slows anything standing in it, like a Frost Trap."),
    _b("proc_damage", "Damage on a chance to proc", "Damage", 6, 43, "aura",
       ["amount"], "While the aura holds, deals damage when the target hits or is hit."),
    _b("instakill", "Kill instantly", "Damage", 1, 0, "instant",
       [], "Kills the target outright, ignoring health. Use sparingly."),

    # --- Healing (continued) --------------------------------------------
    _b("heal_pct", "Heal a share of health", "Healing", 136, 0, "instant",
       ["amount"], "Restores a percentage of the target's maximum health."),
    _b("heal_full", "Heal to full", "Healing", 67, 0, "instant",
       [], "Restores the target to full health."),
    _b("restore_power_pct", "Restore a share of a resource", "Healing", 137, 0, "instant",
       ["amount", "power"], "Restores a percentage of the target's maximum mana or other resource."),
    _b("mod_health_regen", "Change health regeneration", "Healing", 6, 84, "aura",
       ["amount"], "Changes how fast health refills out of combat, per five seconds."),
    _b("mod_health_regen_combat", "Change health regeneration in combat", "Healing", 6, 161, "aura",
       ["amount"], "Changes how fast health refills while fighting, per five seconds."),

    # --- Control (continued) --------------------------------------------
    _b("immune_school", "Immunity to a school", "Control", 6, 39, "aura",
       ["school"], "Makes the target immune to everything of one magic school."),
    _b("immune_effect", "Immunity to an effect type", "Control", 6, 37, "aura",
       ["amount"], "Makes the target immune to one kind of spell effect."),
    _b("pacify_silence", "Silence and prevent attacking", "Control", 6, 60, "aura",
       [], "The target can neither cast nor attack, but is otherwise free to move."),
    _b("reflect_spells", "Reflect spells", "Control", 6, 28, "aura",
       ["amount"], "Sends a share of incoming spells back at their caster."),
    _b("mod_cc_duration", "Change crowd control duration", "Control", 6, 232, "aura",
       ["amount", "mechanic"], "Shortens or lengthens one kind of crowd control on the target."),
    _b("add_combo_points", "Add combo points", "Control", 80, 0, "instant",
       ["amount"], "Awards combo points on the target."),
    _b("dispel_mechanic", "Remove a crowd control effect", "Control", 108, 0, "instant",
       ["mechanic"], "Strips one kind of crowd control from the target, like a stun or a root."),

    # --- Attributes (continued) -----------------------------------------
    _b("mod_spell_power", "Change spell power", "Attributes", 6, 13, "aura",
       ["amount", "school"], "Adds flat spell damage for a school."),
    _b("mod_healing_power", "Change healing power", "Attributes", 6, 135, "aura",
       ["amount"], "Adds flat healing power."),
    _b("mod_rating", "Change a combat rating", "Attributes", 6, 189, "aura",
       ["amount", "rating"], "Adds crit, haste, hit or another rating."),
    _b("mod_damage_taken", "Change damage taken (flat)", "Attributes", 6, 14, "aura",
       ["amount", "school"], "Adds or removes a flat amount from each hit taken."),
    _b("mod_resistance_pct", "Change resistance by a percentage", "Attributes", 6, 101, "aura",
       ["amount", "school"], "Scales resistance for a school."),
    _b("mod_base_resistance_pct", "Change base armour by a percentage", "Attributes", 6, 142, "aura",
       ["amount", "school"], "Scales armour from items and base values."),
    _b("mod_max_health_pct", "Change maximum health by a percentage", "Attributes", 6, 133, "aura",
       ["amount"], "Scales the target's maximum health."),
    _b("mod_stat_percent", "Change one stat by a percentage", "Attributes", 6, 80, "aura",
       ["amount", "stat"], "Scales a single primary stat."),
    _b("mod_hit_chance", "Change melee hit chance", "Attributes", 6, 54, "aura",
       ["amount"], "Adds percentage points of melee and ranged hit."),
    _b("mod_spell_hit_chance", "Change spell hit chance", "Attributes", 6, 55, "aura",
       ["amount"], "Adds percentage points of spell hit."),
    _b("mod_attack_speed_slow", "Slow attack speed", "Attributes", 6, 193, "aura",
       ["amount"], "Slows melee swings by a percentage."),
    _b("mod_expertise", "Change expertise", "Attributes", 6, 240, "aura",
       ["amount"], "Adds expertise rating, reducing dodge and parry against the target."),
    _b("mod_armor_penetration", "Change armour penetration", "Attributes", 6, 280, "aura",
       ["amount"], "Adds armour penetration rating."),
    _b("mod_block_value", "Change block value", "Attributes", 6, 158, "aura",
       ["amount"], "Changes how much damage a shield block absorbs."),
    _b("mod_target_resistance", "Change spell penetration", "Attributes", 6, 123, "aura",
       ["amount", "school"], "Reduces the resistance of the caster's targets."),
    _b("mod_spell_power_from_stat", "Spell power from a stat", "Attributes", 6, 174, "aura",
       ["amount", "stat"], "Grants spell power equal to a percentage of one stat."),
    _b("mod_skill", "Change a skill", "Attributes", 6, 30, "aura",
       ["amount", "skill"], "Raises or lowers a weapon or profession skill."),

    # --- Utility (continued) --------------------------------------------
    _b("fly", "Flight", "Utility", 6, 201, "aura",
       ["amount"], "Lets the target fly. Only works where flying is allowed."),
    _b("feather_fall", "Feather fall", "Utility", 6, 105, "aura",
       ["amount"], "Slows the target's descent without removing fall damage entirely."),
    _b("detect_invisibility", "See invisible", "Utility", 6, 19, "aura",
       ["amount"], "Lets the target see through invisibility of matching strength."),
    _b("force_cast", "Force the target to cast", "Utility", 140, 0, "instant",
       ["trigger"], "Makes the target cast a spell of the caster's choosing."),
    _b("trigger_missile", "Launch a missile that casts a spell", "Utility", 32, 0, "instant",
       ["trigger"], "Fires a projectile at a spot which casts a second spell on landing."),
    _b("proc_trigger_with_value", "Cast a spell on proc, with a value", "Utility", 6, 227, "periodic",
       ["amount", "period", "trigger"], "Casts a second spell each tick and hands it an amount."),
    _b("add_target_trigger", "Cast a spell when your spells land", "Utility", 6, 109, "aura",
       ["amount", "trigger"], "Fires a second spell when the caster's own spells hit, on a chance."),
    _b("force_reaction", "Change faction standing", "Utility", 6, 139, "aura",
       ["amount"], "Makes one faction treat the target as friendly or hostile while it holds."),
    _b("phase", "Move to a phase", "Utility", 6, 261, "aura",
       ["amount"], "Puts the target in a phase, hiding them from players in other phases."),

    # --- Final pass: the remaining behaviours seen 20+ times in stock data ---
    _b("mana_shield", "Absorb damage using mana", "Healing", 6, 97, "aura",
       ["amount"], "Soaks up damage by spending the target's mana instead of their health."),
    _b("mod_power_cost", "Change resource cost", "Attributes", 6, 72, "aura",
       ["amount", "school"], "Scales what the target's spells cost to cast."),
    _b("mod_attack_power_pct", "Change attack power by a percentage", "Attributes", 6, 166, "aura",
       ["amount"], "Scales melee attack power."),
    _b("mod_healing_taken", "Change healing received (flat)", "Attributes", 6, 115, "aura",
       ["amount"], "Adds or removes a flat amount from each heal the target receives."),
    _b("mod_resistance_exclusive", "Change resistance (strongest wins)", "Attributes", 6, 143, "aura",
       ["amount", "school"], "Resistance that does not stack; only the largest such buff applies."),
    _b("mod_block_chance", "Change block chance", "Attributes", 6, 51, "aura",
       ["amount"], "Adds percentage points of shield block chance."),
    _b("mod_ranged_haste", "Change ranged attack speed", "Attributes", 6, 140, "aura",
       ["amount"], "Scales ranged weapon speed. Positive is faster."),
    _b("mod_spell_crit_school", "Change spell crit for one school", "Attributes", 6, 71, "aura",
       ["amount", "school"], "Adds spell crit chance against one magic school only."),
    _b("mod_healing_from_stat", "Healing power from a stat", "Attributes", 6, 175, "aura",
       ["amount", "stat"], "Grants healing power equal to a percentage of one stat."),
    _b("mod_damage_from_caster", "Change damage taken from the caster", "Attributes", 6, 271, "aura",
       ["amount"], "Scales damage this target takes from the caster only."),
    _b("mod_mana_regen_while_casting", "Mana regeneration while casting", "Attributes", 6, 134, "aura",
       ["amount"], "Lets a share of mana regeneration continue during casting."),
    _b("mod_mechanic_damage_taken", "Change damage taken from one mechanic", "Attributes", 6, 255, "aura",
       ["amount", "mechanic"], "Scales damage taken from attacks of one mechanic, such as bleeds."),
    _b("swim_speed", "Change swim speed", "Movement", 6, 58, "aura",
       ["amount"], "Scales how fast the target swims."),
    _b("slow_everything", "Slow movement, attacks and casting", "Movement", 6, 252, "aura",
       ["amount"], "One aura that slows movement, swings and cast times together."),
    _b("immune_damage", "Immunity to damage", "Control", 6, 40, "aura",
       ["school"], "The target takes no damage of the given school."),
    _b("immune_state", "Immunity to an aura type", "Control", 6, 38, "aura",
       ["amount"], "Makes the target immune to one kind of aura, and clears it on apply."),
    _b("mod_mechanic_resistance", "Resistance to a control effect", "Control", 6, 117, "aura",
       ["amount", "mechanic"], "A percentage chance to resist one kind of crowd control."),
    _b("reflect_spells_school", "Reflect spells of one school", "Control", 6, 74, "aura",
       ["amount", "school"], "Sends spells of a single school back at their caster."),
    _b("taunt_attack_me", "Force an attack", "Control", 114, 0, "instant",
       ["amount"], "Forces a creature to switch to the caster, without the threat change."),
    _b("drop_combat", "Drop out of combat", "Utility", 79, 0, "instant",
       ["amount"], "Removes the caster from combat and clears threat, like Vanish."),
    _b("pull_towards", "Pull the target in", "Utility", 124, 0, "instant",
       ["amount"], "Drags the target to the caster."),
    _b("leap_back", "Leap backwards", "Utility", 138, 0, "instant",
       ["amount"], "Throws the caster away from the target, like Disengage."),
    _b("charge_to_location", "Charge to a location", "Utility", 149, 0, "instant",
       ["amount"], "Rushes the caster to a targeted spot rather than to a unit."),
    _b("track_creatures", "Track creatures", "Utility", 6, 44, "aura",
       ["amount"], "Shows creatures of one type on the minimap."),
]

BY_KEY = {b.key: b for b in BEHAVIOURS}

# Any aura behaviour can be applied to a single target with APPLY_AURA, or
# radiated from the caster to a group with one of the APPLY_AREA_AURA_* effects.
# That is a second axis rather than a second set of behaviours: "Mark of the
# Wild" and "Gift of the Wild" are the same behaviour applied two ways. The UI
# offers the behaviour once and asks who it lands on.
APPLICATION_MODES = [
    (6, "single", "The target only"),
    (65, "raid", "Everyone in the caster's raid, within range"),
    (35, "party", "Everyone in the caster's party, within range"),
    (128, "friend", "All friendly units near the caster"),
    (129, "enemy", "All enemies near the caster"),
    (119, "pet", "The caster's pet"),
    (143, "owner", "The pet's owner"),
]

AREA_AURA_EFFECTS = frozenset(e for e, _, _ in APPLICATION_MODES if e != 6)

# Effects and auras that are real, common, and deliberately not offered.
# Recorded so the report can show its own blind spots rather than hide them.
WITHHELD = {
    (3, 0): "DUMMY - does nothing without a C++ SpellScript attached",
    (77, 0): "SCRIPT_EFFECT - does nothing without a C++ SpellScript attached",
    (6, 4): "aura DUMMY - does nothing without a C++ SpellScript attached",
    (6, 226): "aura PERIODIC_DUMMY - does nothing without a C++ SpellScript attached",
    (61, 0): "SEND_EVENT - drives map scripting, not a spell behaviour",
    (6, 107): "ADD_FLAT_MODIFIER - only modifies other spells, via class spell masks",
    (6, 108): "ADD_PCT_MODIFIER - only modifies other spells, via class spell masks",
    (6, 112): "OVERRIDE_CLASS_SCRIPTS - hardcoded per-script ids",
    (24, 0): "CREATE_ITEM - profession recipes, needs an item to exist first",
    (53, 0): "ENCHANT_ITEM - needs a SpellItemEnchantment row",
    (5, 0): "TELEPORT_UNITS - needs coordinates in spell_target_position",
    (6, 2): "MOD_POSSESS - takes control of the target; easy to get stuck in",
    (6, 6): "MOD_CHARM - takes control of the target; easy to get stuck in",
    (74, 0): "APPLY_GLYPH - needs a Glyph.dbc entry",
    (6, 36): "MOD_SHAPESHIFT - needs a SpellShapeshiftForm row",
    (118, 0): "SKILL - grants a skill line, not a spell behaviour",
    (47, 0): "TRADE_SKILL - grants a profession, not a spell behaviour",
    (60, 0): "PROFICIENCY - grants weapon proficiency, not a spell behaviour",
    (33, 0): "OPEN_LOCK - needs lock ids and a target object",
    (50, 0): "TRANS_DOOR - summons a gameobject, needs one to exist first",
    (90, 0): "KILL_CREDIT - quest plumbing",
    (6, 78): "MOUNTED - needs a creature display; mount spells are their own job",
    (16, 0): "QUEST_COMPLETE - quest plumbing",
    (134, 0): "KILL_CREDIT2 - quest plumbing",
    (139, 0): "CLEAR_QUEST - quest plumbing",
    (103, 0): "REPUTATION - quest plumbing",
    (86, 0): "ACTIVATE_OBJECT - needs a gameobject to act on",
    (76, 0): "SUMMON_OBJECT_WILD - needs a gameobject template",
    (87, 0): "GAMEOBJECT_DAMAGE - only meaningful against destructible objects",
    (123, 0): "SEND_TAXI - needs a flight path id",
    (44, 0): "SKILL_STEP - raises a skill line's cap, not a spell behaviour",
    (157, 0): "CREATE_ITEM_2 - profession recipes, needs an item to exist first",
    (54, 0): "ENCHANT_ITEM_TEMPORARY - needs a SpellItemEnchantment row",
    (56, 0): "SUMMON_PET - hunter and warlock pet plumbing",
    (57, 0): "LEARN_PET_SPELL - pet training plumbing",
    (100, 0): "INEBRIATE - drunkenness, not a spell behaviour",
    (43, 0): "TELEPORT_UNITS_FACE_CASTER - needs coordinates in spell_target_position",
    (6, 32): "MOD_INCREASE_MOUNTED_SPEED - part of mount spells",
    (6, 207): "MOD_INCREASE_MOUNTED_FLIGHT_SPEED - part of mount spells",
    (6, 236): "CONTROL_VEHICLE - needs a vehicle definition",
    (6, 260): "SCREEN_EFFECT - a client-side full-screen filter",
    (6, 284): "LINKED - links auras together by id; needs matching spells to exist",
    (6, 102): "MOD_MELEE_ATTACK_POWER_VERSUS - only applies against one creature type",
    (6, 131): "MOD_RANGED_ATTACK_POWER_VERSUS - only applies against one creature type",
    (6, 197): "MOD_ATTACKER_SPELL_AND_WEAPON_CRIT_CHANCE - affects attackers, rarely wanted",
    (6, 20): "OBS_MOD_HEALTH - legacy percentage-based regeneration",
    (6, 147): "MECHANIC_IMMUNITY_MASK - a bitmask of mechanics; use the single-mechanic immunity",
    (6, 0): "APPLY_AURA with no aura - a no-op left in the data",
    (104, 0): "SUMMON_OBJECT_SLOT1 - totem and trap slots, needs a gameobject",
    (45, 0): "ADD_HONOR - PvP plumbing",
    (133, 0): "UNLEARN_SPECIALIZATION - profession plumbing",
    (153, 0): "CREATE_TAMED_PET - hunter pet plumbing",
    (6, 177): "AOE_CHARM - mass mind control; easy to get stuck in",
    (41, 0): "JUMP - needs a destination the core computes per spell",
    (29, 0): "LEAP - needs a destination the core computes per spell",
    (6, 303): "MOD_DAMAGE_DONE_VERSUS_AURASTATE - conditional on an aura state id",
    (6, 168): "MOD_DAMAGE_DONE_VERSUS - only applies against one creature type",
    (6, 206): "MOD_INCREASE_FLIGHT_SPEED - part of flying mount spells",
    (6, 186): "MOD_ATTACKER_SPELL_HIT_CHANCE - affects attackers, rarely wanted",
    (6, 184): "MOD_ATTACKER_MELEE_HIT_CHANCE - affects attackers, rarely wanted",
}
