"""Regenerate spellweaver/enums.py from the AzerothCore source headers.

The effect, aura, target and mechanic id spaces are defined by the server, not
by us. Rather than transcribing ~800 constants by hand we parse them out of the
headers, so the mapping can never drift from the core we write rows for.
"""
import pathlib
import re

AC = pathlib.Path.home() / "AzerothCore/azerothcore-wotlk/src"
SHARED = AC / "server/shared/SharedDefines.h"
AURAS = AC / "server/game/Spells/Auras/SpellAuraDefines.h"


def parse_enum(path, enum_name, prefix):
    """Pull NAME = <int> pairs out of one C++ enum block."""
    text = path.read_text(encoding="utf-8", errors="replace")
    m = re.search(r"enum %s\b[^\n{]*\n?\s*\{" % enum_name, text)
    if not m:
        raise SystemExit("could not find enum %s in %s" % (enum_name, path))
    start = m.end()
    end = text.index("\n};", start)
    out = {}
    for line in text[start:end].splitlines():
        m = re.match(r"\s*(%s\w*)\s*=\s*(\d+)\s*[,}]?" % prefix, line)
        if not m:
            continue
        # First name wins, so aliases defined later don't shadow the real one.
        out.setdefault(int(m.group(2)), m.group(1)[len(prefix):] or "NONE")
    return out


TABLES = [
    ("SPELL_EFFECTS", SHARED, "SpellEffects", "SPELL_EFFECT_"),
    ("SPELL_AURAS", AURAS, "AuraType", "SPELL_AURA_"),
    ("SPELL_TARGETS", SHARED, "Targets", "TARGET_"),
    ("SPELL_MECHANICS", SHARED, "Mechanics", "MECHANIC_"),
]

dest = pathlib.Path(__file__).resolve().parent.parent / "spellweaver/enums.py"
with dest.open("w") as f:
    f.write('"""Generated by tools/gen_enums.py from AzerothCore headers. Do not edit."""\n\n')
    for varname, path, enum, prefix in TABLES:
        table = parse_enum(path, enum, prefix)
        # Drop the TOTAL_/MAX_ sentinels that terminate these enums.
        table = {k: v for k, v in table.items() if not v.startswith(("TOTAL", "MAX_"))}
        f.write("%s = {\n" % varname)
        for k in sorted(table):
            f.write("    %d: %r,\n" % (k, table[k]))
        f.write("}\n\n")
        print("%-16s %4d entries (max id %d)" % (varname, len(table), max(table)))
print("wrote", dest)
