#!/usr/bin/env python3
"""Regenerate spellweaver/spell_layout.py from the live spell_dbc schema.

AzerothCore keeps spell_dbc's column order in 1:1 correspondence with the 234
fields of Spell.dbc, so the live schema is the cheapest authoritative source for
the DBC layout. Run this if you ever move to a core with a different schema.
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from spellweaver.config import load_settings, require_connection
from spellweaver.mysql import connect

EXPECTED_FIELDS = 234
OUT = pathlib.Path(__file__).resolve().parent.parent / "spellweaver/spell_layout.py"

# Fields whose four bytes are a float rather than an int. The DBC itself does
# not say which is which, so the layout has to.
FLOAT_PREFIXES = ("EffectRealPointsPerLevel", "EffectMultipleValue",
                  "EffectChainAmplitude", "EffectBonusMultiplier", "EffectAmplitude")
FLOAT_NAMES = {"Speed"}


def columns(settings):
    with connect(settings.db) as db:
        _, rows = db.query(
            "SELECT COLUMN_NAME FROM information_schema.COLUMNS "
            "WHERE TABLE_SCHEMA = '%s' AND TABLE_NAME = 'spell_dbc' "
            "ORDER BY ORDINAL_POSITION" % settings.db.world_db)
    return [r[0] for r in rows]


def main():
    settings = require_connection(load_settings())
    cols = columns(settings)
    if len(cols) != EXPECTED_FIELDS:
        raise SystemExit(
            "spell_dbc has %d columns, expected %d. This core's schema does not "
            "match 3.3.5a's Spell.dbc." % (len(cols), EXPECTED_FIELDS))

    floats = {c for c in cols if c.startswith(FLOAT_PREFIXES)} | FLOAT_NAMES
    strings = [c for c in cols if "_Lang_" in c and not c.endswith("_Lang_Mask")]

    body = ['"""Generated by tools/gen_layout.py from the live spell_dbc schema.',
            'Do not edit."""', "",
            "FIELDS = ["]
    body += ["    %r," % c for c in cols]
    body += ["]", "",
             "INDEX = {name: i for i, name in enumerate(FIELDS)}", "",
             "FLOAT_FIELDS = frozenset(%r)" % sorted(floats), "",
             "STRING_FIELDS = frozenset(%r)" % sorted(strings), ""]
    OUT.write_text("\n".join(body))
    print("wrote %s: %d fields, %d floats, %d strings"
          % (OUT, len(cols), len(floats), len(strings)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
